------------------------------------------------------------
-- 1️⃣ SEQUENCES
------------------------------------------------------------

CREATE SEQUENCE foundation_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE hospital_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE bloodbank_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE bloodstock_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE employee_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE donor_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE customer_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE appointment_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE order_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE invoice_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE transaction_seq START WITH 1 INCREMENT BY 1 NOCACHE;

------------------------------------------------------------
-- 2️⃣ AUTO-ID TRIGGERS
------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_foundation_id
BEFORE INSERT ON Foundation
FOR EACH ROW
BEGIN
  IF :NEW.F_id IS NULL THEN
    SELECT foundation_seq.NEXTVAL INTO :NEW.F_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_hospital_id
BEFORE INSERT ON Hospital
FOR EACH ROW
BEGIN
  IF :NEW.Hs_id IS NULL THEN
    SELECT hospital_seq.NEXTVAL INTO :NEW.Hs_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_bloodbank_id
BEFORE INSERT ON Bloodbank
FOR EACH ROW
BEGIN
  IF :NEW.BB_id IS NULL THEN
    SELECT bloodbank_seq.NEXTVAL INTO :NEW.BB_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_bloodstock_id
BEFORE INSERT ON BloodStock
FOR EACH ROW
BEGIN
  IF :NEW.BS_id IS NULL THEN
    SELECT bloodstock_seq.NEXTVAL INTO :NEW.BS_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_employee_id
BEFORE INSERT ON Employee
FOR EACH ROW
BEGIN
  IF :NEW.E_id IS NULL THEN
    SELECT employee_seq.NEXTVAL INTO :NEW.E_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_donor_id
BEFORE INSERT ON Donor
FOR EACH ROW
BEGIN
  IF :NEW.D_id IS NULL THEN
    SELECT donor_seq.NEXTVAL INTO :NEW.D_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_customer_id
BEFORE INSERT ON Customer
FOR EACH ROW
BEGIN
  IF :NEW.C_id IS NULL THEN
    SELECT customer_seq.NEXTVAL INTO :NEW.C_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_appointment_id
BEFORE INSERT ON Appointment
FOR EACH ROW
BEGIN
  IF :NEW.App_id IS NULL THEN
    SELECT appointment_seq.NEXTVAL INTO :NEW.App_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_order_id
BEFORE INSERT ON Ord
FOR EACH ROW
BEGIN
  IF :NEW.Or_id IS NULL THEN
    SELECT order_seq.NEXTVAL INTO :NEW.Or_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_invoice_id
BEFORE INSERT ON Invoice
FOR EACH ROW
BEGIN
  IF :NEW.In_id IS NULL THEN
    SELECT invoice_seq.NEXTVAL INTO :NEW.In_id FROM dual;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_transaction_id
BEFORE INSERT ON Transactionstab
FOR EACH ROW
BEGIN
  IF :NEW.T_id IS NULL THEN
    SELECT transaction_seq.NEXTVAL INTO :NEW.T_id FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- 3️⃣ BUSINESS LOGIC TRIGGERS
------------------------------------------------------------

------------------------------------------------------------
-- A) Donor History Update on Donation Completed
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_update_donor_history
AFTER UPDATE OF App_status ON Appointment
FOR EACH ROW
WHEN (NEW.App_status = 'Completed' AND OLD.App_status <> 'Completed')
BEGIN
    UPDATE Donor
    SET D_history = NVL(D_history,0) + 1
    WHERE D_id = :NEW.D1_id;
END;
/

------------------------------------------------------------
-- B) Update BloodBank Stock on Donation Completion
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_update_blood_stock
AFTER UPDATE OF App_status ON Appointment
FOR EACH ROW
WHEN (NEW.App_status = 'Completed' AND OLD.App_status <> 'Completed')
BEGIN
    UPDATE Bloodbank
    SET BB_volume = NVL(BB_volume,0) + 1
    WHERE BB_id = :NEW.BB2_id;
END;
/

------------------------------------------------------------
-- C) Prevent Duplicate Donor Contacts
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_prevent_duplicate_donor
BEFORE INSERT ON Donor
FOR EACH ROW
DECLARE v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count 
    FROM Donor 
    WHERE D_contact = :NEW.D_contact;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Duplicate donor contact detected.');
    END IF;
END;
/

------------------------------------------------------------
-- D) Appointment Status Audit
------------------------------------------------------------
CREATE TABLE Appointment_Audit (
    Audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    App_id NUMBER,
    Old_status VARCHAR2(20),
    New_status VARCHAR2(20),
    Updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_appointment_audit
AFTER UPDATE OF App_status ON Appointment
FOR EACH ROW
BEGIN
    INSERT INTO Appointment_Audit (App_id,Old_status,New_status)
    VALUES (:OLD.App_id,:OLD.App_status,:NEW.App_status);
END;
/

------------------------------------------------------------
-- END OF TRIGGERS.SQL
------------------------------------------------------------
