------------------------------------------------------------
-- BLOOD DONATION DATABASE SYSTEM – COMPLETE TRIGGERS & SEQUENCES
-- Author: Ashika
-- Description: Automated logic for donor, appointment, invoice,
-- transaction, audit, and data consistency.
------------------------------------------------------------

------------------------------------------------------------
-- Safe-Drop Utility Blocks (allow re-execution)
------------------------------------------------------------

-- 🧹 Drop sequences if they already exist
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE appointment_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE donor_seq';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 🧹 Drop audit tables if they already exist
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Donor_Audit CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Appointment_Audit CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 🧹 Drop triggers if already defined
BEGIN
  FOR t IN (SELECT trigger_name FROM user_triggers WHERE trigger_name LIKE 'TRG_%') LOOP
    EXECUTE IMMEDIATE 'DROP TRIGGER ' || t.trigger_name;
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 1️⃣  Trigger: Update donor’s donation history
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_update_donor_history
AFTER INSERT OR UPDATE ON Appointment
FOR EACH ROW
WHEN (NEW.App_status = 'Completed')
BEGIN
    UPDATE Donor
    SET D_history = NVL(D_history, 0) + 1
    WHERE D_id = :NEW.D1_id;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 2️⃣  Trigger: Mark order as billed when invoice is created
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_invoice_mark_order
AFTER INSERT ON Invoice
FOR EACH ROW
BEGIN
    UPDATE Ord
    SET Or_status = 'Billed'
    WHERE Or_id = :NEW.Or1_id;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 3️⃣  Trigger: Mark invoice as paid when transaction succeeds
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_invoice_paid
AFTER INSERT ON Transactionstab
FOR EACH ROW
BEGIN
    IF :NEW.T_status = 'Success' THEN
        UPDATE Invoice
        SET In_status = 'Paid'
        WHERE In_id = :NEW.In1_id;
    END IF;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 4️⃣  Sequence & Trigger: Auto-generate Appointment ID
------------------------------------------------------------
CREATE SEQUENCE appointment_seq
  START WITH 606
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
/
CREATE OR REPLACE TRIGGER trg_appointment_id
BEFORE INSERT ON Appointment
FOR EACH ROW
BEGIN
  IF :NEW.App_id IS NULL THEN
    SELECT appointment_seq.NEXTVAL INTO :NEW.App_id FROM dual;
  END IF;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 5️⃣  Sequence & Trigger: Auto-generate Donor ID
------------------------------------------------------------
CREATE SEQUENCE donor_seq
  START WITH 504
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
/
CREATE OR REPLACE TRIGGER trg_donor_id
BEFORE INSERT ON Donor
FOR EACH ROW
BEGIN
  IF :NEW.D_id IS NULL THEN
    SELECT donor_seq.NEXTVAL INTO :NEW.D_id FROM dual;
  END IF;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 6️⃣  Donor Registration Audit Table + Trigger
------------------------------------------------------------
CREATE TABLE Donor_Audit (
    Audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    D_id NUMBER(10),
    D_name VARCHAR2(15),
    D_contact NUMBER(10),
    D_address VARCHAR2(255),
    D_age NUMBER(3),
    D_gender VARCHAR2(6),
    D_history NUMBER(10),
    BB3_id NUMBER(10),
    App1_id NUMBER(10),
    Registration_date TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_donor_registration_audit
AFTER INSERT ON Donor
FOR EACH ROW
BEGIN
    INSERT INTO Donor_Audit (
        D_id, D_name, D_contact, D_address, D_age, D_gender,
        D_history, BB3_id, App1_id
    )
    VALUES (
        :NEW.D_id, :NEW.D_name, :NEW.D_contact, :NEW.D_address, :NEW.D_age,
        :NEW.D_gender, :NEW.D_history, :NEW.BB3_id, :NEW.App1_id
    );
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 7️⃣  Trigger: Prevent invalid blood donations
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_prevent_invalid_donation
BEFORE INSERT OR UPDATE ON Appointment
FOR EACH ROW
DECLARE
    v_age Donor.D_age%TYPE;
    v_history Donor.D_history%TYPE;
BEGIN
    SELECT D_age, D_history INTO v_age, v_history
    FROM Donor
    WHERE D_id = :NEW.D1_id;

    IF v_age < 18 OR v_age > 65 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Donor age not eligible for donation.');
    END IF;

    IF v_history >= 10 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Donor has reached maximum donation limit.');
    END IF;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 8️⃣  Trigger: Record blood stock when donation completes
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_update_blood_stock
AFTER UPDATE OF App_status ON Appointment
FOR EACH ROW
WHEN (NEW.App_status = 'Completed' AND OLD.App_status != 'Completed')
BEGIN
  UPDATE Bloodbank
  SET BB_volume = NVL(BB_volume, 0) + 1
  WHERE BB_id = :NEW.BB2_id;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 9️⃣  Trigger: Prevent duplicate donor registration
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_prevent_duplicate_donor
BEFORE INSERT ON Donor
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM Donor
    WHERE D_contact = :NEW.D_contact;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Donor already registered with this contact number.');
    END IF;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 🔟  Appointment Audit Table + Trigger
------------------------------------------------------------
CREATE TABLE Appointment_Audit (
    Audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    App_id NUMBER,
    Old_status VARCHAR2(10),
    New_status VARCHAR2(10),
    Updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_appointment_audit
AFTER UPDATE OF App_status ON Appointment
FOR EACH ROW
BEGIN
    INSERT INTO Appointment_Audit (App_id, Old_status, New_status)
    VALUES (:OLD.App_id, :OLD.App_status, :NEW.App_status);
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 1️⃣1️⃣  Trigger: Auto-update Hospital Order Count
------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE Hospital DROP COLUMN Hs_order_count';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
ALTER TABLE Hospital ADD (Hs_order_count NUMBER DEFAULT 0);
/
CREATE OR REPLACE TRIGGER trg_update_hospital_orders
AFTER INSERT ON Ord
FOR EACH ROW
BEGIN
    UPDATE Hospital
    SET Hs_order_count = NVL(Hs_order_count, 0) + 1
    WHERE Hs_id = :NEW.Hs2_id;
END;
/
------------------------------------------------------------

------------------------------------------------------------
-- 1️⃣2️⃣  Trigger: Auto-delete appointments when donor deleted
------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_delete_appointments_on_donor_delete
AFTER DELETE ON Donor
FOR EACH ROW
BEGIN
    DELETE FROM Appointment WHERE D1_id = :OLD.D_id;
END;
/
------------------------------------------------------------
COMMIT;
------------------------------------------------------------
-- ✅ END OF TRIGGERS.SQL
------------------------------------------------------------
